/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useState, useEffect} from 'react';
import {StyleSheet, Text, View, Button} from 'react-native';
import PointSdkRn from 'react-native-point-sdk';

const App = () => {
  const [apiKey, setApiKey] = useState('not defined');

  useEffect(() => {
    PointSdkRn.setup('abc123', function callback(_, result) {
      setApiKey(result);
    });
  }, []);

  const handleRequestPermissions = async () => {
    try {
      await PointSdkRn.requestPermissions();
      console.log(true);
    } catch (error) {
      console.log(error);
    }
  };

  const handleLogin = async () => {
    try {
      await PointSdkRn.login('abc123');
      console.log(true);
    } catch (error) {
      console.log(error);
    }
  };

  const handleLogout = async () => {
    try {
      const result = await PointSdkRn.logout();
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>☆PointSdkRn example☆</Text>
      <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
      <Text style={styles.instructions}>Received Api Key: {apiKey}</Text>
      <Button
        onPress={handleRequestPermissions}
        title="Request Permissions"
        color="#841584"
        accessibilityLabel="Request Permissions"
      />
      <Button
        onPress={handleLogin}
        title="Login"
        color="#841584"
        accessibilityLabel="Login"
      />
      <Button
        onPress={handleLogout}
        title="Logout"
        color="#841584"
        accessibilityLabel="Logout"
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

export default App;
