/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useState, useEffect} from 'react';
import {StyleSheet, Text, View, Button} from 'react-native';
import PointSdkRn from 'react-native-point-sdk';

const App = () => {
  const [apiKey, setApiKey] = useState('not defined');
  const [workouts, setWorkouts] = useState([]);

  async function foobar() {
    const workouts = await PointSdkRn.getUserWorkouts(0);
    console.log(workouts);
    setWorkouts(workouts);
  }

  useEffect(() => {
    PointSdkRn.setup('abc123', function callback(_, result) {
      setApiKey(result);
    });
  }, []);

  const handleRequestPermissions = async () => {
    try {
      const result = await PointSdkRn.requestPermissions(
        PointSdkRn.healthPermissions,
      );
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  };

  const handleLogin = async () => {
    // eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9wb2ludC1hcHAtZGV2LnVzLmF1dGgwLmNvbS8ifQ..2k9y9Cp7945h0T4I.XdUPlgT1CHi7RF0e4RnKEpiip0_Mx0vRWdKRxqT9tH9toqmXlgLwrlA1xpl_kkfPCUPv-Uktwl7YTeAXBZfS-xhS1cOifuYRzWJABlZzcc1UIUCI7mf98fsW_nmf7TkdX89MrPlMRYs5hDcJ3tOOSnFdR4kjjuyNCBNyl0P6PKLfewv9m8ehODCNsGMS2hc9xK8eA2uTaWsLv-asrtfow87uz-JmH_HEm8brYeZbYk4lRQH_g2XDacXZzI5OGHCeE3O4UPw5M5rpEBGu4EzLEst4FY_x1YRKieSj72OaMhpbiY39i8GB-W4R2_Jb57nhEpCJ62mtzcRlGOSgI7ulVNIdO8bl2sYK-T8BpWyPmk_gCWor.jYzC6HoGDHtiH6iUZOCF4w
    try {
      await PointSdkRn.login(
        'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9wb2ludC1hcHAtZGV2LnVzLmF1dGgwLmNvbS8ifQ..2k9y9Cp7945h0T4I.XdUPlgT1CHi7RF0e4RnKEpiip0_Mx0vRWdKRxqT9tH9toqmXlgLwrlA1xpl_kkfPCUPv-Uktwl7YTeAXBZfS-xhS1cOifuYRzWJABlZzcc1UIUCI7mf98fsW_nmf7TkdX89MrPlMRYs5hDcJ3tOOSnFdR4kjjuyNCBNyl0P6PKLfewv9m8ehODCNsGMS2hc9xK8eA2uTaWsLv-asrtfow87uz-JmH_HEm8brYeZbYk4lRQH_g2XDacXZzI5OGHCeE3O4UPw5M5rpEBGu4EzLEst4FY_x1YRKieSj72OaMhpbiY39i8GB-W4R2_Jb57nhEpCJ62mtzcRlGOSgI7ulVNIdO8bl2sYK-T8BpWyPmk_gCWor.jYzC6HoGDHtiH6iUZOCF4w',
      );
      console.log(true);
    } catch (error) {
      console.log(error);
    }
  };

  const handleLogout = async () => {
    try {
      const result = await PointSdkRn.logout();
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  };

  const handleStartBackgroundListener = async () => {
    try {
      const result = await PointSdkRn.startBackgroundListener();
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  };

  const handleStopBackgroundListener = async () => {
    try {
      const result = await PointSdkRn.stopBackgroundListener();
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>☆PointSdkRn example☆</Text>
      <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
      <Text style={styles.instructions}>Received Api Key: {apiKey}</Text>
      <Button
        onPress={handleRequestPermissions}
        title="Request Permissions"
        color="blue"
        accessibilityLabel="Request Permissions"
      />
      <Button
        onPress={handleLogin}
        title="Login"
        color="blue"
        accessibilityLabel="Login"
      />
      <Button
        onPress={handleLogout}
        title="Logout"
        color="red"
        accessibilityLabel="Logout"
      />
      {/* <Button
        onPress={handleStartBackgroundListener}
        title="Start Background Listener"
        color="green"
        accessibilityLabel="Start Background Listener"
      />
      <Button
        onPress={handleStopBackgroundListener}
        title="Stop Background Listener"
        color="red"
        accessibilityLabel="Stop Background Listener"
      /> */}
      <Button
        onPress={foobar}
        title="Get Workouts"
        color="red"
        accessibilityLabel="Stop Background Listener"
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

export default App;
