/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useState, useEffect} from 'react';
import {Button, Text, View, FlatList} from 'react-native';
import PointSdkRn from 'react-native-point-sdk';
import styled from 'styled-components/native';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';

function HomeScreen() {
  const [user, setUser] = useState(null);

  const handleRequestPermissions = async () => {
    try {
      const result = await PointSdkRn.requestPermissions(
        PointSdkRn.healthPermissions,
      );
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  };

  const handleLogin = async () => {
    try {
      await PointSdkRn.login(
        'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9wb2ludC1hcHAtZGV2LnVzLmF1dGgwLmNvbS8ifQ..uid-c9Gz9IAiN5T8.0sZiHvFJfusDcyXoe5Llw1A7oZkEwCgmwsr9VX2jtp2UJqtScSHpkLmA6soGQ64avyLs9qb6xTTeOiewm4WF_9E-v5bunQ1ey2G8sCM0udqtdPnVzOuM1uqUSlJDTV1zOFdLTpRegQIIBRxT-WVMIamGL4WcTa3exingT7eyU_RHLwn4LcEjz55uyDZzOhbsHUz_xAq3bJ9yHIHHCBCsYdDgTfIx-i2OSjuT38MDicXVmm2vFBIxalJDBGbjhTXLDYLnONpeZytV89pAjIdNme750jMZWwGH47rx6a4amYi9XhPtBuNiUC5yYqcvvwj7m_gkAlWuFKECCIU7l4XxVZ2THRbw0m-zNdIfD2tc6ZFfkHRCDYsJssZuFJ3LAydBvF8qzojJ.xQ6MD5_l2OFnLg88F6Xg4w',
      );
      const userData = await PointSdkRn.getUserData();
      setUser(userData);
      console.log('Successfully logged in');
    } catch (error) {
      console.log(error);
    }
  };

  const handleLogout = async () => {
    try {
      await PointSdkRn.logout();
      setUser(null);
      console.log('Successfully logged out');
    } catch (error) {
      console.log(error);
    }
  };

  const handleStartBackgroundListener = async () => {
    try {
      const result = await PointSdkRn.startBackgroundListener();
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  };

  const handleStopBackgroundListener = async () => {
    try {
      const result = await PointSdkRn.stopBackgroundListener();
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      {user && (
        <Text style={{fontSize: 18, fontWeight: 'bold'}}>
          Welcome, {user.email}!
        </Text>
      )}
      <Button onPress={handleRequestPermissions} title="Request Permissions" />
      <Button onPress={handleLogin} title="Login" />
      <Button onPress={handleLogout} title="Logout" />
      <Button
        onPress={handleStartBackgroundListener}
        title="Start Background Listener"
      />
      <Button
        onPress={handleStopBackgroundListener}
        title="Stop Background Listener"
      />
    </View>
  );
}

function WorkoutsScreen() {
  const [workouts, setWorkouts] = useState([]);

  async function getWorkouts() {
    setWorkouts([]);
    setWorkouts(await PointSdkRn.getUserWorkouts(0));
  }

  return (
    <View>
      <Button onPress={getWorkouts} title="Get Workouts" />
      <FlatList
        data={workouts}
        renderItem={({item}) => (
          <WorkoutItem>
            <Text>ID: {item.id}</Text>
            <Text>Calories: {item.calories}</Text>
            <Text>Duration: {item.duration}</Text>
            <Text>Start: {item.start}</Text>
            <Text>End: {item.end}</Text>
          </WorkoutItem>
        )}
      />
    </View>
  );
}

const Tab = createBottomTabNavigator();

const App = () => {
  useEffect(() => {
    PointSdkRn.setup('abc123', console.log);
  }, []);

  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen} />
        <Tab.Screen name="Workouts" component={WorkoutsScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
};

const WorkoutItem = styled.View`
  border-bottom-width: 1px;
  border-bottom-color: #ccc;
  padding: 10px;
`;

export default App;
